# Generated by Django 2.1.5 on 2019-01-29 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BerthType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berth_type', models.CharField(blank=True, max_length=25, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'berth_type',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_nbr', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='PassangerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='M', max_length=10)),
                ('with_child', models.BooleanField(default=False)),
                ('berth_preference_id', models.ForeignKey(db_column='berth_preference_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='railway.BerthType')),
            ],
            options={
                'db_table': 'passanger_detail',
            },
        ),
        migrations.CreateModel(
            name='SeqCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_nbr', models.IntegerField(blank=True, default='0')),
                ('counter_code', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'db_table': 'seq_counter',
            },
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_nbr', models.CharField(max_length=30, unique=True)),
                ('booked_ts', models.DateTimeField(auto_now=True)),
                ('mod_ts', models.DateTimeField(auto_now=True)),
                ('date_of_journey', models.DateField(auto_now=True)),
                ('berth_type_id', models.ForeignKey(db_column='berth_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='railway.BerthType')),
                ('coach_id', models.ForeignKey(db_column='coach_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='railway.Coach')),
            ],
            options={
                'db_table': 'ticket_detail',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ticket_status',
            },
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='railway.TicketStatus'),
        ),
        migrations.AddField(
            model_name='passangerdetail',
            name='ticket_id',
            field=models.ForeignKey(db_column='ticket_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='railway.TicketDetail'),
        ),
    ]
